# Generated by Django 3.1.5 on 2021-06-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='money',
            field=models.FloatField(default=0),
        ),
    ]
